name = "ColSpecF"
description = "ColSpecF is a Fortran library for evaluating mathematical Special Functions."
author = "Rodrigo Castro"
version = "0.1.0"
license = "LICENSE"
maintainer = "rodpcastro18@gmail.com"
categories = ["mathematics", "special-functions", "numerical-computing", "scientific-computing"]

[install]
library = true

[dependencies]
test-drive = {git = "https://github.com/fortran-lang/test-drive.git" }
